name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # این را به نام شاخه اصلی خود تغییر دهید اگر متفاوت است

permissions:
  contents: write # این مجوز برای نوشتن در شاخه gh-pages لازم است

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist